version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: jobportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: jobportal
      MYSQL_DATABASE: jobportal
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: